---

- name: Include OS-specific variables.
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution|lower }}_{{ ansible_distribution_major_version }}.yaml'
    - '{{ ansible_distribution|lower }}.yaml'
    - '{{ ansible_os_family|lower }}_{{ ansible_distribution_major_version }}.yaml'
    - '{{ ansible_os_family|lower }}.yaml'

- name: Install BackupPC packages
  package:
    name: '{{ backuppc__packages }}'

- include_tasks: freebsd.yml
  when:
    - ansible_os_family == "FreeBSD"
